/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-18 at 21:59:50 UTC 
 * Modify at your own risk.
 */

package edu.uno.csci4661.grocerylist.groceryitemendpoint;

/**
 * Service definition for Groceryitemendpoint (v1).
 * <p/>
 * <p>
 * This is an API
 * </p>
 * <p/>
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 * <p/>
 * <p>
 * This service uses {@link GroceryitemendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @author Google, Inc.
 * @since 1.3
 */
@SuppressWarnings("javadoc")
public class Groceryitemendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

    // Note: Leave this static initializer at the top of the file.
    static {
        com.google.api.client.util.Preconditions.checkState(
                com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
                        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
                "You are currently running with version %s of google-api-client. " +
                        "You need at least version 1.15 of google-api-client to run version " +
                        "1.17.0-rc of the groceryitemendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
    }

    /**
     * The default encoded root URL of the service. This is determined when the library is generated
     * and normally should not be changed.
     *
     * @since 1.7
     */
    public static final String DEFAULT_ROOT_URL = "https://csci4661-api.appspot.com/_ah/api/";

    /**
     * The default encoded service path of the service. This is determined when the library is
     * generated and normally should not be changed.
     *
     * @since 1.7
     */
    public static final String DEFAULT_SERVICE_PATH = "groceryitemendpoint/v1/";

    /**
     * The default encoded base URL of the service. This is determined when the library is generated
     * and normally should not be changed.
     */
    public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

    /**
     * Constructor.
     * <p/>
     * <p>
     * Use {@link Builder} if you need to specify any of the optional parameters.
     * </p>
     *
     * @param transport              HTTP transport, which should normally be:
     *                               <ul>
     *                               <li>Google App Engine:
     *                               {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *                               <li>Android: {@code newCompatibleTransport} from
     *                               {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *                               <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *                               </li>
     *                               </ul>
     * @param jsonFactory            JSON factory, which may be:
     *                               <ul>
     *                               <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *                               <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *                               <li>Android Honeycomb or higher:
     *                               {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *                               </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Groceryitemendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
                               com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
        this(new Builder(transport, jsonFactory, httpRequestInitializer));
    }

    /**
     * @param builder builder
     */
    Groceryitemendpoint(Builder builder) {
        super(builder);
    }

    @Override
    protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
        super.initialize(httpClientRequest);
    }

    /**
     * Create a request for the method "getGroceryItem".
     * <p/>
     * This request holds the parameters needed by the groceryitemendpoint server.  After setting any
     * optional parameters, call the {@link GetGroceryItem#execute()} method to invoke the remote
     * operation.
     *
     * @param id
     * @return the request
     */
    public GetGroceryItem getGroceryItem(java.lang.Long id) throws java.io.IOException {
        GetGroceryItem result = new GetGroceryItem(id);
        initialize(result);
        return result;
    }

    public class GetGroceryItem extends GroceryitemendpointRequest<edu.uno.csci4661.grocerylist.groceryitemendpoint.model.GroceryItem> {

        private static final String REST_PATH = "groceryitem/{id}";

        /**
         * Create a request for the method "getGroceryItem".
         * <p/>
         * This request holds the parameters needed by the the groceryitemendpoint server.  After setting
         * any optional parameters, call the {@link GetGroceryItem#execute()} method to invoke the remote
         * operation. <p> {@link GetGroceryItem#initialize(com.google.api.client.googleapis.services.Abstr
         * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
         * the constructor. </p>
         *
         * @param id
         * @since 1.13
         */
        protected GetGroceryItem(java.lang.Long id) {
            super(Groceryitemendpoint.this, "GET", REST_PATH, null, edu.uno.csci4661.grocerylist.groceryitemendpoint.model.GroceryItem.class);
            this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
        }

        @Override
        public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
            return super.executeUsingHead();
        }

        @Override
        public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
            return super.buildHttpRequestUsingHead();
        }

        @Override
        public GetGroceryItem setAlt(java.lang.String alt) {
            return (GetGroceryItem) super.setAlt(alt);
        }

        @Override
        public GetGroceryItem setFields(java.lang.String fields) {
            return (GetGroceryItem) super.setFields(fields);
        }

        @Override
        public GetGroceryItem setKey(java.lang.String key) {
            return (GetGroceryItem) super.setKey(key);
        }

        @Override
        public GetGroceryItem setOauthToken(java.lang.String oauthToken) {
            return (GetGroceryItem) super.setOauthToken(oauthToken);
        }

        @Override
        public GetGroceryItem setPrettyPrint(java.lang.Boolean prettyPrint) {
            return (GetGroceryItem) super.setPrettyPrint(prettyPrint);
        }

        @Override
        public GetGroceryItem setQuotaUser(java.lang.String quotaUser) {
            return (GetGroceryItem) super.setQuotaUser(quotaUser);
        }

        @Override
        public GetGroceryItem setUserIp(java.lang.String userIp) {
            return (GetGroceryItem) super.setUserIp(userIp);
        }

        @com.google.api.client.util.Key
        private java.lang.Long id;

        /**

         */
        public java.lang.Long getId() {
            return id;
        }

        public GetGroceryItem setId(java.lang.Long id) {
            this.id = id;
            return this;
        }

        @Override
        public GetGroceryItem set(String parameterName, Object value) {
            return (GetGroceryItem) super.set(parameterName, value);
        }
    }

    /**
     * Create a request for the method "insertGroceryItem".
     * <p/>
     * This request holds the parameters needed by the groceryitemendpoint server.  After setting any
     * optional parameters, call the {@link InsertGroceryItem#execute()} method to invoke the remote
     * operation.
     *
     * @param content the {@link edu.uno.csci4661.grocerylist.groceryitemendpoint.model.GroceryItem}
     * @return the request
     */
    public InsertGroceryItem insertGroceryItem(edu.uno.csci4661.grocerylist.groceryitemendpoint.model.GroceryItem content) throws java.io.IOException {
        InsertGroceryItem result = new InsertGroceryItem(content);
        initialize(result);
        return result;
    }

    public class InsertGroceryItem extends GroceryitemendpointRequest<edu.uno.csci4661.grocerylist.groceryitemendpoint.model.GroceryItem> {

        private static final String REST_PATH = "groceryitem";

        /**
         * Create a request for the method "insertGroceryItem".
         * <p/>
         * This request holds the parameters needed by the the groceryitemendpoint server.  After setting
         * any optional parameters, call the {@link InsertGroceryItem#execute()} method to invoke the
         * remote operation. <p> {@link InsertGroceryItem#initialize(com.google.api.client.googleapis.serv
         * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
         * invoking the constructor. </p>
         *
         * @param content the {@link edu.uno.csci4661.grocerylist.groceryitemendpoint.model.GroceryItem}
         * @since 1.13
         */
        protected InsertGroceryItem(edu.uno.csci4661.grocerylist.groceryitemendpoint.model.GroceryItem content) {
            super(Groceryitemendpoint.this, "POST", REST_PATH, content, edu.uno.csci4661.grocerylist.groceryitemendpoint.model.GroceryItem.class);
        }

        @Override
        public InsertGroceryItem setAlt(java.lang.String alt) {
            return (InsertGroceryItem) super.setAlt(alt);
        }

        @Override
        public InsertGroceryItem setFields(java.lang.String fields) {
            return (InsertGroceryItem) super.setFields(fields);
        }

        @Override
        public InsertGroceryItem setKey(java.lang.String key) {
            return (InsertGroceryItem) super.setKey(key);
        }

        @Override
        public InsertGroceryItem setOauthToken(java.lang.String oauthToken) {
            return (InsertGroceryItem) super.setOauthToken(oauthToken);
        }

        @Override
        public InsertGroceryItem setPrettyPrint(java.lang.Boolean prettyPrint) {
            return (InsertGroceryItem) super.setPrettyPrint(prettyPrint);
        }

        @Override
        public InsertGroceryItem setQuotaUser(java.lang.String quotaUser) {
            return (InsertGroceryItem) super.setQuotaUser(quotaUser);
        }

        @Override
        public InsertGroceryItem setUserIp(java.lang.String userIp) {
            return (InsertGroceryItem) super.setUserIp(userIp);
        }

        @Override
        public InsertGroceryItem set(String parameterName, Object value) {
            return (InsertGroceryItem) super.set(parameterName, value);
        }
    }

    /**
     * Create a request for the method "listGroceryItem".
     * <p/>
     * This request holds the parameters needed by the groceryitemendpoint server.  After setting any
     * optional parameters, call the {@link ListGroceryItem#execute()} method to invoke the remote
     * operation.
     *
     * @return the request
     */
    public ListGroceryItem listGroceryItem() throws java.io.IOException {
        ListGroceryItem result = new ListGroceryItem();
        initialize(result);
        return result;
    }

    public class ListGroceryItem extends GroceryitemendpointRequest<edu.uno.csci4661.grocerylist.groceryitemendpoint.model.CollectionResponseGroceryItem> {

        private static final String REST_PATH = "groceryitem";

        /**
         * Create a request for the method "listGroceryItem".
         * <p/>
         * This request holds the parameters needed by the the groceryitemendpoint server.  After setting
         * any optional parameters, call the {@link ListGroceryItem#execute()} method to invoke the remote
         * operation. <p> {@link ListGroceryItem#initialize(com.google.api.client.googleapis.services.Abst
         * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
         * the constructor. </p>
         *
         * @since 1.13
         */
        protected ListGroceryItem() {
            super(Groceryitemendpoint.this, "GET", REST_PATH, null, edu.uno.csci4661.grocerylist.groceryitemendpoint.model.CollectionResponseGroceryItem.class);
        }

        @Override
        public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
            return super.executeUsingHead();
        }

        @Override
        public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
            return super.buildHttpRequestUsingHead();
        }

        @Override
        public ListGroceryItem setAlt(java.lang.String alt) {
            return (ListGroceryItem) super.setAlt(alt);
        }

        @Override
        public ListGroceryItem setFields(java.lang.String fields) {
            return (ListGroceryItem) super.setFields(fields);
        }

        @Override
        public ListGroceryItem setKey(java.lang.String key) {
            return (ListGroceryItem) super.setKey(key);
        }

        @Override
        public ListGroceryItem setOauthToken(java.lang.String oauthToken) {
            return (ListGroceryItem) super.setOauthToken(oauthToken);
        }

        @Override
        public ListGroceryItem setPrettyPrint(java.lang.Boolean prettyPrint) {
            return (ListGroceryItem) super.setPrettyPrint(prettyPrint);
        }

        @Override
        public ListGroceryItem setQuotaUser(java.lang.String quotaUser) {
            return (ListGroceryItem) super.setQuotaUser(quotaUser);
        }

        @Override
        public ListGroceryItem setUserIp(java.lang.String userIp) {
            return (ListGroceryItem) super.setUserIp(userIp);
        }

        @com.google.api.client.util.Key
        private java.lang.String cursor;

        /**

         */
        public java.lang.String getCursor() {
            return cursor;
        }

        public ListGroceryItem setCursor(java.lang.String cursor) {
            this.cursor = cursor;
            return this;
        }

        @com.google.api.client.util.Key
        private java.lang.Integer limit;

        /**

         */
        public java.lang.Integer getLimit() {
            return limit;
        }

        public ListGroceryItem setLimit(java.lang.Integer limit) {
            this.limit = limit;
            return this;
        }

        @Override
        public ListGroceryItem set(String parameterName, Object value) {
            return (ListGroceryItem) super.set(parameterName, value);
        }
    }

    /**
     * Create a request for the method "removeGroceryItem".
     * <p/>
     * This request holds the parameters needed by the groceryitemendpoint server.  After setting any
     * optional parameters, call the {@link RemoveGroceryItem#execute()} method to invoke the remote
     * operation.
     *
     * @param id
     * @return the request
     */
    public RemoveGroceryItem removeGroceryItem(java.lang.Long id) throws java.io.IOException {
        RemoveGroceryItem result = new RemoveGroceryItem(id);
        initialize(result);
        return result;
    }

    public class RemoveGroceryItem extends GroceryitemendpointRequest<edu.uno.csci4661.grocerylist.groceryitemendpoint.model.GroceryItem> {

        private static final String REST_PATH = "groceryitem/{id}";

        /**
         * Create a request for the method "removeGroceryItem".
         * <p/>
         * This request holds the parameters needed by the the groceryitemendpoint server.  After setting
         * any optional parameters, call the {@link RemoveGroceryItem#execute()} method to invoke the
         * remote operation. <p> {@link RemoveGroceryItem#initialize(com.google.api.client.googleapis.serv
         * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
         * invoking the constructor. </p>
         *
         * @param id
         * @since 1.13
         */
        protected RemoveGroceryItem(java.lang.Long id) {
            super(Groceryitemendpoint.this, "DELETE", REST_PATH, null, edu.uno.csci4661.grocerylist.groceryitemendpoint.model.GroceryItem.class);
            this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
        }

        @Override
        public RemoveGroceryItem setAlt(java.lang.String alt) {
            return (RemoveGroceryItem) super.setAlt(alt);
        }

        @Override
        public RemoveGroceryItem setFields(java.lang.String fields) {
            return (RemoveGroceryItem) super.setFields(fields);
        }

        @Override
        public RemoveGroceryItem setKey(java.lang.String key) {
            return (RemoveGroceryItem) super.setKey(key);
        }

        @Override
        public RemoveGroceryItem setOauthToken(java.lang.String oauthToken) {
            return (RemoveGroceryItem) super.setOauthToken(oauthToken);
        }

        @Override
        public RemoveGroceryItem setPrettyPrint(java.lang.Boolean prettyPrint) {
            return (RemoveGroceryItem) super.setPrettyPrint(prettyPrint);
        }

        @Override
        public RemoveGroceryItem setQuotaUser(java.lang.String quotaUser) {
            return (RemoveGroceryItem) super.setQuotaUser(quotaUser);
        }

        @Override
        public RemoveGroceryItem setUserIp(java.lang.String userIp) {
            return (RemoveGroceryItem) super.setUserIp(userIp);
        }

        @com.google.api.client.util.Key
        private java.lang.Long id;

        /**

         */
        public java.lang.Long getId() {
            return id;
        }

        public RemoveGroceryItem setId(java.lang.Long id) {
            this.id = id;
            return this;
        }

        @Override
        public RemoveGroceryItem set(String parameterName, Object value) {
            return (RemoveGroceryItem) super.set(parameterName, value);
        }
    }

    /**
     * Create a request for the method "updateGroceryItem".
     * <p/>
     * This request holds the parameters needed by the groceryitemendpoint server.  After setting any
     * optional parameters, call the {@link UpdateGroceryItem#execute()} method to invoke the remote
     * operation.
     *
     * @param content the {@link edu.uno.csci4661.grocerylist.groceryitemendpoint.model.GroceryItem}
     * @return the request
     */
    public UpdateGroceryItem updateGroceryItem(edu.uno.csci4661.grocerylist.groceryitemendpoint.model.GroceryItem content) throws java.io.IOException {
        UpdateGroceryItem result = new UpdateGroceryItem(content);
        initialize(result);
        return result;
    }

    public class UpdateGroceryItem extends GroceryitemendpointRequest<edu.uno.csci4661.grocerylist.groceryitemendpoint.model.GroceryItem> {

        private static final String REST_PATH = "groceryitem";

        /**
         * Create a request for the method "updateGroceryItem".
         * <p/>
         * This request holds the parameters needed by the the groceryitemendpoint server.  After setting
         * any optional parameters, call the {@link UpdateGroceryItem#execute()} method to invoke the
         * remote operation. <p> {@link UpdateGroceryItem#initialize(com.google.api.client.googleapis.serv
         * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
         * invoking the constructor. </p>
         *
         * @param content the {@link edu.uno.csci4661.grocerylist.groceryitemendpoint.model.GroceryItem}
         * @since 1.13
         */
        protected UpdateGroceryItem(edu.uno.csci4661.grocerylist.groceryitemendpoint.model.GroceryItem content) {
            super(Groceryitemendpoint.this, "PUT", REST_PATH, content, edu.uno.csci4661.grocerylist.groceryitemendpoint.model.GroceryItem.class);
        }

        @Override
        public UpdateGroceryItem setAlt(java.lang.String alt) {
            return (UpdateGroceryItem) super.setAlt(alt);
        }

        @Override
        public UpdateGroceryItem setFields(java.lang.String fields) {
            return (UpdateGroceryItem) super.setFields(fields);
        }

        @Override
        public UpdateGroceryItem setKey(java.lang.String key) {
            return (UpdateGroceryItem) super.setKey(key);
        }

        @Override
        public UpdateGroceryItem setOauthToken(java.lang.String oauthToken) {
            return (UpdateGroceryItem) super.setOauthToken(oauthToken);
        }

        @Override
        public UpdateGroceryItem setPrettyPrint(java.lang.Boolean prettyPrint) {
            return (UpdateGroceryItem) super.setPrettyPrint(prettyPrint);
        }

        @Override
        public UpdateGroceryItem setQuotaUser(java.lang.String quotaUser) {
            return (UpdateGroceryItem) super.setQuotaUser(quotaUser);
        }

        @Override
        public UpdateGroceryItem setUserIp(java.lang.String userIp) {
            return (UpdateGroceryItem) super.setUserIp(userIp);
        }

        @Override
        public UpdateGroceryItem set(String parameterName, Object value) {
            return (UpdateGroceryItem) super.set(parameterName, value);
        }
    }

    /**
     * Builder for {@link Groceryitemendpoint}.
     * <p/>
     * <p>
     * Implementation is not thread-safe.
     * </p>
     *
     * @since 1.3.0
     */
    public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

        /**
         * Returns an instance of a new builder.
         *
         * @param transport              HTTP transport, which should normally be:
         *                               <ul>
         *                               <li>Google App Engine:
         *                               {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
         *                               <li>Android: {@code newCompatibleTransport} from
         *                               {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
         *                               <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
         *                               </li>
         *                               </ul>
         * @param jsonFactory            JSON factory, which may be:
         *                               <ul>
         *                               <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
         *                               <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
         *                               <li>Android Honeycomb or higher:
         *                               {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
         *                               </ul>
         * @param httpRequestInitializer HTTP request initializer or {@code null} for none
         * @since 1.7
         */
        public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
                       com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
            super(
                    transport,
                    jsonFactory,
                    DEFAULT_ROOT_URL,
                    DEFAULT_SERVICE_PATH,
                    httpRequestInitializer,
                    false);
        }

        /**
         * Builds a new instance of {@link Groceryitemendpoint}.
         */
        @Override
        public Groceryitemendpoint build() {
            return new Groceryitemendpoint(this);
        }

        @Override
        public Builder setRootUrl(String rootUrl) {
            return (Builder) super.setRootUrl(rootUrl);
        }

        @Override
        public Builder setServicePath(String servicePath) {
            return (Builder) super.setServicePath(servicePath);
        }

        @Override
        public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
            return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
        }

        @Override
        public Builder setApplicationName(String applicationName) {
            return (Builder) super.setApplicationName(applicationName);
        }

        @Override
        public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
            return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
        }

        @Override
        public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
            return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
        }

        @Override
        public Builder setSuppressAllChecks(boolean suppressAllChecks) {
            return (Builder) super.setSuppressAllChecks(suppressAllChecks);
        }

        /**
         * Set the {@link GroceryitemendpointRequestInitializer}.
         *
         * @since 1.12
         */
        public Builder setGroceryitemendpointRequestInitializer(
                GroceryitemendpointRequestInitializer groceryitemendpointRequestInitializer) {
            return (Builder) super.setGoogleClientRequestInitializer(groceryitemendpointRequestInitializer);
        }

        @Override
        public Builder setGoogleClientRequestInitializer(
                com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
            return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
        }
    }
}
